<a href="https://colab.research.google.com/github/PujaSridhar/Profit-Prediction-of-50-startups/blob/main/Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Reading the data 
data=pd.read_csv("/content/50_Startups.csv")
X = data.iloc[:,:-1].values
y = data.iloc[:,3].values
#y1=y.reshape(-1,1)
print(X)
print(y)

[[165349.2  136897.8  471784.1 ]
 [162597.7  151377.59 443898.53]
 [153441.51 101145.55 407934.54]
 [144372.41 118671.85 383199.62]
 [142107.34  91391.77 366168.42]
 [131876.9   99814.71 362861.36]
 [134615.46 147198.87 127716.82]
 [130298.13 145530.06 323876.68]
 [120542.52 148718.95 311613.29]
 [123334.88 108679.17 304981.62]
 [101913.08 110594.11 229160.95]
 [100671.96  91790.61 249744.55]
 [ 93863.75 127320.38 249839.44]
 [ 91992.39 135495.07 252664.93]
 [119943.24 156547.42 256512.92]
 [114523.61 122616.84 261776.23]
 [ 78013.11 121597.55 264346.06]
 [ 94657.16 145077.58 282574.31]
 [ 91749.16 114175.79 294919.57]
 [ 86419.7  153514.11      0.  ]
 [ 76253.86 113867.3  298664.47]
 [ 78389.47 153773.43 299737.29]
 [ 73994.56 122782.75 303319.26]
 [ 67532.53 105751.03 304768.73]
 [ 77044.01  99281.34 140574.81]
 [ 64664.71 139553.16 137962.62]
 [ 75328.87 144135.98 134050.07]
 [ 72107.6  127864.55 353183.81]
 [ 66051.52 182645.56 118148.2 ]
 [ 65605.48 153032.06 107138.38]
 [ 61994.4

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   Profit           50 non-null     float64
dtypes: float64(4)
memory usage: 1.7 KB


In [ ]:
data[data.duplicated()]

Empty DataFrame
Columns: [R&D Spend, Administration, Marketing Spend, Profit]
Index: []

In [ ]:
data.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [ ]:
#The data is being split into train and test data 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [ ]:
#LINEAR REGRESION
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train,y_train)
lin_reg.predict(X_test)
#y_pred=y_pred.reshape(-1,1)
print("Training Score: ",lin_reg.score(X_train,y_train))
print("Testing Score: ",lin_reg.score(X_test, y_test))


Training Score:  0.9499572530324031
Testing Score:  0.9393955917820571


In [ ]:
#RMSE AND CROSS VAL SCORE FOR THE LINEAR REGRESSION MODEL
from sklearn.metrics import mean_squared_error
y_pred_lin = lin_reg.predict(X_test)
lin_mse = mean_squared_error(y_test, y_pred_lin)
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)
from sklearn.model_selection import cross_val_score
scores_lin = cross_val_score(lin_reg, X_test, y_test,scoring="neg_mean_squared_error", cv=10)
lin_rmse_scores = np.sqrt(-scores_lin)
def display_scores(scores_lin):
  print("Scores:", scores_lin)
  print("Mean:", scores_lin.mean())
  print("Standard deviation:", scores_lin.std())
display_scores(lin_rmse_scores)

8803.77579046934
Scores: [ 7571.76567448  1511.48494076  5652.27017806  5315.20072441
 12935.62577368  4188.84822832  9578.94908815  7987.6029029
  1078.08446274 16091.92217316]
Mean: 7191.175414665971
Standard deviation: 4508.1354832906145


In [ ]:
#SVM REGRESSION
from sklearn.svm import LinearSVR
svm_reg = LinearSVR(epsilon=1.5)
svm_reg.fit(X_train, y_train)
y_pred1 = svm_reg.predict(X_test)
print("Training Score: ",svm_reg.score(X_train,y_train))
print("Testing Score: ",svm_reg.score(X_test, y_test))

Training Score:  0.882068908244534
Testing Score:  0.7431206933263099


/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


In [ ]:
#RMSE AND CROSS VAL SCORE FOR THE SVM REGRESSION MODEL
from sklearn.metrics import mean_squared_error
y_pred_svr = svm_reg.predict(X_test)
svr_mse = mean_squared_error(y_test, y_pred_svr)
svr_rmse = np.sqrt(svr_mse)
print(svr_rmse)
from sklearn.model_selection import cross_val_score
scores_svr = cross_val_score(svm_reg, X_test, y_test,scoring="neg_mean_squared_error", cv=10)
svr_rmse_scores = np.sqrt(-scores_svr)
def display_scores(scores_svr):
  print("Scores:", scores_svr)
  print("Mean:", scores_svr.mean())
  print("Standard deviation:", scores_svr.std())
display_scores(svr_rmse_scores)

18125.142364170344
Scores: [12423.2271989  31157.17238073 44869.44112841 27492.31500512
 33933.03240068 43637.39333295 11325.40636923  1481.92714891
 48525.34776388 18446.49060383]
Mean: 27329.175333264982
Standard deviation: 15187.093092023679


/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number

In [ ]:
#DECISION TREE REGGRESOR
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor(max_depth=2)
tree_reg.fit(X_train, y_train)
tree_reg.predict(X_test)
print("Training Score: ",tree_reg.score(X_train,y_train))
print("Testing Score: ",tree_reg.score(X_test, y_test))

Training Score:  0.89089652193947
Testing Score:  0.7718995412718883


In [ ]:
#RMSE AND CROSS VAL SCORE FOR THE DECISION TREE REGRESSION MODEL
from sklearn.metrics import mean_squared_error
y_pred_tree = tree_reg.predict(X_test)
tree_mse = mean_squared_error(y_test, y_pred_tree)
tree_rmse = np.sqrt(tree_mse)
print("RMSE: ",tree_rmse)
from sklearn.model_selection import cross_val_score
scores_tree = cross_val_score(tree_reg, X_test, y_test,scoring="neg_mean_squared_error", cv=10)
tree_rmse_scores = np.sqrt(-scores_tree)
def display_scores(scores_tree):
  print("Scores:", scores_tree)
  print("Mean:", scores_tree.mean())
  print("Standard deviation:", scores_tree.std())
display_scores(tree_rmse_scores)

RMSE:  17079.688493281377
Scores: [  998.99333333 11895.545      44928.44        3430.23
 24862.45        1302.24666667  3430.23        8730.75333333
  8427.5        24862.45      ]
Mean: 13286.883833333337
Standard deviation: 13432.84903311609


In [ ]:
#RANDOM FOREST REGRESSOR
from sklearn.ensemble import RandomForestRegressor
forest_reg = RandomForestRegressor()
forest_reg.fit(X_train, y_train)
forest_reg.predict(X_test)
print("Training Score: ",forest_reg.score(X_train,y_train))
print("Testing Score: ",forest_reg.score(X_test, y_test))


Training Score:  0.989860463708382
Testing Score:  0.9604386214392272


In [ ]:
#RMSE AND CROSS VAL SCORE FOR THE RANODOM FOREST REGRESSOR REGRESSION MODEL
from sklearn.metrics import mean_squared_error
y_pred_forest = forest_reg.predict(X_test)
forest_mse = mean_squared_error(y_test, y_pred_forest)
forest_rmse = np.sqrt(forest_mse)
print("RMSE: ",forest_rmse)
from sklearn.model_selection import cross_val_score
scores_forest = cross_val_score(forest_reg, X_test, y_test,scoring="neg_mean_squared_error", cv=10)
forest_rmse_scores = np.sqrt(-scores_forest)
def display_scores(scores_forest):
  print("Scores:", scores_forest)
  print("Mean:", scores_forest.mean())
  print("Standard deviation:", scores_forest.std())
display_scores(forest_rmse_scores)

RMSE:  7112.996165399267
Scores: [ 4776.7508 15337.0538 10367.7443 15807.0816 37567.1979 13310.9556
 12197.2163  6425.8502  3124.6904  5334.7648]
Mean: 12424.93057000003
Standard deviation: 9425.340631655505


The prediction of profit across 50 startups is found using four different regression model [Linear regression, SVR, Decision Tree regressor and Random forest regressor] The best model is the Linear regressor as the score of the model is around 93% which is the best compared to the rest 